# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Verify Project

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pyproject.toml'
      - 'poetry.toml'
      - 'poetry.lock'
      - 'setup.cfg'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'pyproject.toml'
      - 'poetry.toml'
      - 'poetry.lock'
      - 'setup.cfg'

jobs:
  build:
    name: Build with ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry==1.1.14
        poetry install
    - name: Check code quality
      run: |
        poetry run black --check .
        poetry run isort . --check --diff
        poetry run flake8 . --count --show-source --statistics
    - name: Test Run
      run: |
        poetry run python -m src.app
